if(EXISTS "/home/wolf/Code/miniob/src/unitest/log_test[1]_tests.cmake")
  include("/home/wolf/Code/miniob/src/unitest/log_test[1]_tests.cmake")
else()
  add_test(log_test_NOT_BUILT log_test_NOT_BUILT)
endif()
