if(EXISTS "/home/wolf/Code/miniob/src/unitest/rc_test[1]_tests.cmake")
  include("/home/wolf/Code/miniob/src/unitest/rc_test[1]_tests.cmake")
else()
  add_test(rc_test_NOT_BUILT rc_test_NOT_BUILT)
endif()
